name: static_intl
description: Static String generator for Flutter
version: 0.0.1
author: Saulo Andrioli
homepage:

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
